name: CD
on:
  # 以主干的push事件作为触发条件
  push:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest # 构建运行环境
    steps:

      - name: Install & Build # 安装依赖打包静态资源
        run: |
          yarn config set registry https://registry.npm.taobao.org
          yarn install
          yarn build
